version: '3.2'

services:
  elasticsearch:
    container_name: elasticsearch
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: 7.8.1
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk
    healthcheck:
        test: ["CMD", "curl", "-f", "http://127.0.0.1:9200"]
        interval: 30s
        timeout: 10s
        retries: 5

  mytoysgroup-product-app:
    restart: on-failure
    build: ./
    expose:
      - "8080"
    ports:
      - 8080:8080
    depends_on:
      - elasticsearch
    environment:
      - WAIT_HOSTS=elasticsearch:9200   
      
networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:


